# complete
[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  source $HOME/.config/nvim/config/deoplete.vim
'''

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'tpope/vim-dispatch'


# Exploler
[[plugins]]
repo = 'nvim-neo-tree/neo-tree.nvim'
depends = ['nvim-lua/plenary.nvim', 'nvim-tree/nvim-web-devicons', 'MunifTanjim/nui.nvim']
hook_add = '''
  source $HOME/.config/nvim/config/neotree.lua
'''

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'nvim-tree/nvim-web-devicons'

[[plugins]]
repo = 'MunifTanjim/nui.nvim'

# statusline
[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

# 無駄な空白をハイライト
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# `gcc`でコメント化
[[plugins]]
repo = 'tomtom/tcomment_vim'

# colors
[[plugins]]
repo = 'jacoborus/tender.vim'

# syntaxes
[[plugins]]
repo = 'leafgarland/typescript-vim'

